#!/usr/bin/env bash
# a script that redirects /redirect_me to another page

sudo apt update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
sudo sed -i '/server_name _;/a\rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart