#!/usr/bin/env bash
# a script that redirects /redirect_me to another page

sudo apt update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
sudo sed -i "/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4/ permanent;" /etc/nginx/sites-available/default
sudo service nginx restart