#!/usr/bin/env bash
# script that installs and configures HAproxy on the lb-01 server.

sudo apt update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
frontend http_front
        bind :80
        stats uri /haproxy?stats
        default_backend server_group
backend server_group
        balance roundrobin
        server 229663-web-01 34.203.29.35:80 check
        server 229663-web-02 100.25.3.77:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
