#!/usr/bin/env bash
# this script:- creates a file /var/run/myscript.pid containing its PID
# displays "To infinity and beyond" indefinitely with sleep 2 after each interval
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
handle_termination() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid
while ((1)); do
	echo "To infinity and beyond"
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && handle_termination' SIGTERM
	trap 'handle_termination' SIGQUIT
done
