#!/usr/bin/env bash
# this script displays "To inifinity and beyond" indefinitely with sleep 2 after each iteration, "I am invincible !!!" when receiving a SIGTERM signal
while ((1)); do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
