#!/usr/bin/env bash
# this script displays numbers 1-100 with certain words at certain intervals
for ((i= 1; i <= 100; i++));do
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
