#!/usr/bin/env bash
# this script displays the time for 12 hours and 59 minutes
hr=0
while ((hr <= 12));do
	echo "Hour: $hr"

	min=1	
	while ((min <= 59));do
		echo "$min"
		((min++))
	done
	((hr++))
done
