#!/usr/bin/env bash
# this script displays content of the current directory in a list format
for file in *; do
	if [ -f "$file" ] && [[ "$file" != .* ]]
	then
		after_dash=$(echo "$file" | cut -d"-" -f2-)
		echo "$after_dash"
	fi
done
