#!/usr/bin/env bash
# script that ensures that Nginx is running as the nginx user
sudo pkill -f apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart 
